apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: playk-s
build:
  artifacts:
  - image: gcr.io/hitsuji-haneta/playk8s/main
    context: ./main
  - image: gcr.io/hitsuji-haneta/playk8s/sub
    context: ./sub
  local:
    useBuildkit: true
deploy:
  kustomize:
    paths: ["./manifests/"]