apiVersion: apps/v1
kind: Deployment
metadata:
  name: playk8s-deployment
  labels:
    app: playk8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playk8s
  template:
    metadata:
      labels:
        app: playk8s
    spec:
      containers:
      - name: playk8s-container
        image: gcr.io/hitsuji-haneta/playk8s:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: playk8s-volume
          mountPath: /app/templates
        - name: secret-volume
          mountPath: /app/secret
      volumes:
      - name: playk8s-volume
        persistentVolumeClaim:
          claimName: pv-slow-claim
      - name: secret-volume
        secret:
          secretName: playk8s-secret
          items:
          - key: prikey
            path: prikey.txt
      terminationGracePeriodSeconds: 0